# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

xwayland {
    force_zero_scaling = true
}

# Per-screen input configuration for Asus Zenbook Duo

# Map the first set of touch and stylus inputs to eDP-1
device {
    name = elan9008:00-04f3:4447
    output = eDP-1
}

device {
    name = elan9008:00-04f3:4447-stylus
    output = eDP-1
}

# Map the second set of touch and stylus inputs to eDP-2
device {
    name = elan9009:00-04f3:4448
    output = eDP-2
}
 
device {
    name = elan9009:00-04f3:4448-stylus
    output = eDP-2
}

# Keyboard options i like to use. This one is for vim so that caps lock gets remapped to escape
input {
    kb_options = caps:escape
}

# Keyboard layouts: US and German, switch between them with Win+Space. Customize to your liking.
input {
    kb_layout=us,de
    kb_options=grp:win_space_toggle
}
